### ISSUE TITLE
Placeholder: Hadoop access in k8s

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSKubernetes#56]
This is a place holder for the consistency checking scripts. How do/can we get access to the same Hadoop in the analytic cluster on a kubernetes pod to read in the results of a job?

**Comment by vkuznet** [comment]
Here is reply from Prasanth:

"...
We have k8s clusters that can read and process data from analytix and this is available from SWAN. We put the software in the image (https://gitlab.cern.ch/db/spark-service/docker-registry/tree/master) and the configuration we take from CVMFS which is mounted to the pods of the executor. You can also include Hadoop config (/etc/hadoop, etc/spark) in the image and set HADOOP_CONF_DIR 
..."

Since they do provide Dockerfile we should be able to take its content and use it in our cmsweb image. I'll work on it later.

**Comment by vkuznet** [comment]
I added initial support for hadoop in this commit:
https://github.com/dmwm/CMSKubernetes/commit/7f9a3d80ea188642d5e63aae6761225036beef12

It needs to be properly configured though and tested afterwards, but so far both hadoop and spark libraries and executables are in place.

**Comment by vkuznet** [comment]
This [document](https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb-nginx/docs/hadoop.md) describe all details what needs to be done. These steps has been tested on cmsweb k8s cluster, closing the ticket.

**Comment by vkuznet** [comment]
We have plenty of examples now to access hadoop from k8s, therefore closign the issue
